'use strict';
const test=require('node:test'), assert=require('node:assert/strict');
const context=require('../../cloudfunctions/mcloud/framework/tenancy/tenant_context.js');
// These cases verify the authorization policy restored after internal testing.
require('../../cloudfunctions/mcloud/config/config.js').ADMIN_LOGIN_CREDENTIALS_ONLY=false;
const {wrap}=require('../../cloudfunctions/mcloud/framework/tenancy/tenant_database.js');
const {memory}=require('../test-support/tenant-memory.cjs');
const A={schoolId:'school_a',campusId:'east'}, B={schoolId:'school_a',campusId:'west'}, C={schoolId:'school_b',campusId:'east'};
function sample(){const f=memory();for(const [id,scope] of [['a',A],['b',B],['c',C]])f.table('bx_mail').set(id,{_id:id,_pid:'crun',...scope,status:0});f.table('bx_mail').set('legacy',{_id:'legacy',_pid:'crun',status:0});return {...f,db:wrap(f.db)};}
test('missing tenant context fails closed for operational collections',()=>{const f=sample();assert.throws(()=>f.db.collection('bx_mail'),/学校|校区/);assert.throws(()=>context.run({schoolId:'../bad',campusId:'east'},()=>{}));});
test('concurrent asynchronous requests retain separate campus contexts',async()=>{const f=sample();let release;const gate=new Promise(r=>release=r);const first=context.run(A,async()=>{await gate;return (await f.db.collection('bx_mail').get()).data;});const second=context.run(B,async()=>{await Promise.resolve();release();return (await f.db.collection('bx_mail').get()).data;});const [a,b]=await Promise.all([first,second]);assert.deepEqual(a.map(x=>x._id),['a']);assert.deepEqual(b.map(x=>x._id),['b']);assert.equal(context.current(),undefined);});
test('scope survives projections, pagination, OR queries and counts',async()=>context.run(A,async()=>{const f=sample();const c=f.db.collection('bx_mail');assert.equal((await c.where(f.db.command.or([{status:0},{campusId:'west'}])).field({status:true}).limit(10).get()).data.length,1);assert.equal((await c.count()).total,1);assert.equal((await c.where({schoolId:'school_b'}).get()).data.length,0);assert.equal((await c.limit(1).count()).total,1);}));
test('foreign and legacy document IDs cannot disclose or overwrite rows',async()=>context.run(A,async()=>{const f=sample();for(const id of ['b','c','legacy']){const d=f.db.collection('bx_mail').doc(id);assert.equal((await d.get()).data,null);await assert.rejects(d.set({data:{status:9}}),/不属于/);await assert.rejects(d.update({data:{status:9}}),/不属于/);await assert.rejects(d.remove(),/不属于/);}assert.equal(f.table('bx_mail').get('b').status,0);}));
test('inserts and transactional writes stamp scope and prevent scope reassignment',async()=>context.run(A,async()=>{const f=sample();await f.db.collection('bx_mail').add({data:{_id:'new',status:1}});assert.deepEqual(f.table('bx_mail').get('new'),{_id:'new',status:1,_pid:'crun',...A});await f.db.runTransaction(async tx=>{await tx.collection('bx_mail').doc('a').update({data:{status:1}});assert.equal((await tx.collection('bx_mail').doc('a').get()).data.status,1);});await assert.rejects(f.db.collection('bx_mail').doc('a').update({data:{campusId:'west'}}));assert.throws(()=>f.db.collection('bx_mail').add({data:{'schoolId.name':'bad'}}));}));
test('batch updates and deletes affect only the active campus',async()=>context.run(A,async()=>{const f=sample();assert.equal((await f.db.collection('bx_mail').where({status:0}).update({data:{status:9}})).stats.updated,1);assert.equal(f.table('bx_mail').get('b').status,0);await f.db.collection('bx_mail').remove();assert.deepEqual([...f.table('bx_mail').keys()],['b','c','legacy']);}));
test('school profiles are shared within a school and hidden from other schools',async()=>{const f=sample();await context.run(A,()=>f.db.collection('bx_user').doc('u').set({data:{name:'student'}}));assert.equal(f.table('bx_user').get('u').campusId,undefined);await context.run(B,async()=>assert.equal((await f.db.collection('bx_user').doc('u').get()).data.name,'student'));await context.run(C,async()=>assert.equal((await f.db.collection('bx_user').doc('u').get()).data,null));});
test('aggregate joins constrain both sides and raw nested pipelines are rejected',async()=>context.run(A,async()=>{const f=sample();await f.db.collection('bx_mail').aggregate().lookup({from:'bx_user',localField:'userId',foreignField:'_id',as:'owner'}).end();const pipeline=f.calls.at(-1).pipeline;assert.deepEqual(pipeline[0].$match,{_pid:'crun',...A});assert.equal(pipeline[1].$lookup.pipeline[0].$match.schoolId,A.schoolId);assert.throws(()=>f.db.collection('bx_mail').aggregate().lookup({from:'bx_user',pipeline:[{$lookup:{from:'bx_mail'}}]}));assert.throws(()=>f.db.collection('bx_mail').aggregate().unionWith('bx_mail'));}));
test('admin scopes cannot be supplied by the client or inferred from role alone',()=>context.run(A,()=>{assert.equal(context.canAdmin({ADMIN_STATUS:1,ADMIN_TYPE:1}),false);assert.equal(context.canAdmin({ADMIN_STATUS:1,ADMIN_TYPE:0,ADMIN_PLATFORM:true}),false);assert.equal(context.canAdmin({ADMIN_STATUS:1,ADMIN_TYPE:0,ADMIN_SCOPES:[{...B}]}),false);assert.equal(context.canAdmin({ADMIN_STATUS:1,ADMIN_TYPE:0,ADMIN_SCOPES:[{schoolId:'school_a',campusId:'*'}]}),true);assert.equal(context.canAdmin({ADMIN_STATUS:0,ADMIN_TYPE:1,ADMIN_PLATFORM:true}),false);}));
test('only explicit server system context can inspect the whole project',async()=>{const f=sample();await context.system(async()=>assert.equal((await f.db.collection('bx_mail').count()).total,4));assert.throws(()=>f.db.collection('bx_mail'));});
