const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');const test=require('node:test');
const root=path.resolve(__dirname,'../..');
function load(file,mocks,globals={}){const module={exports:{}};vm.runInNewContext(fs.readFileSync(path.join(root,file),'utf8'),{module,Buffer,Date,console:{warn(){}},require(name){if(Object.hasOwn(mocks,name))return mocks[name];if(name==='crypto')return require('node:crypto');throw new Error('Unexpected '+name);},...globals});return module.exports;}
function auditFixture(){const state={downloads:0,saved:[],text:[],enabled:true,pass:true,buffer:Buffer.from([137,80,78,71,13,10,26,10,0])};const cloud={getWXContext:()=>({OPENID:'owner'}),async downloadFile(){state.downloads++;return {fileContent:state.buffer};},async uploadFile(p){state.saved.push(p);return {fileID:'cloud://env.bucket/'+p.cloudPath};},openapi:{security:{async imgSecCheck(){return {errCode:state.pass?0:87014};},async msgSecCheck(p){state.text.push(p);return {errCode:0,result:{suggest:state.pass?'pass':'review'}};}}}};const config={get CLIENT_CHECK_CONTENT(){return state.enabled;},ADMIN_CHECK_CONTENT:false};const api=load('cloudfunctions/mcloud/framework/validate/content_check.js',{'../core/app_error.js':Error,'../cloud/cloud_base.js':{getCloud:()=>cloud},'../../config/config.js':config});return {state,api};}
test('evidence accepts only exact owner upload prefix and rejects nested prefix spoofing',async()=>{const {api,state}=auditFixture();for(const id of ['http://bad','cloud://env.bucket/private/other/p.png','cloud://env.bucket/private/other/private/owner/p.png','cloud://env.bucket/private-evidence/owner/p.png'])await assert.rejects(api.checkCloudImage(id));assert.equal(state.downloads,0);});
test('audited evidence is copied server-side and only authorized archived files can be reused',async()=>{const {api,state}=auditFixture();const id=await api.checkCloudImage('cloud://env.bucket/private/owner/p.png');assert.match(id,/^cloud:\/\/env.bucket\/private-evidence\/owner\/[a-f0-9]{64}\.png$/);assert.ok(state.saved[0].fileContent.equals(state.buffer));assert.equal(await api.checkCloudImage(id,[id]),id);assert.equal(state.downloads,1);await assert.rejects(api.checkCloudImage(id,[]));});
test('image size, signature and moderation failures do not create evidence',async()=>{for(const kind of ['size','format','moderation']){const {api,state}=auditFixture();if(kind==='size')state.buffer=Buffer.alloc(1024*1024+1);if(kind==='format')state.buffer=Buffer.from('<svg/>');if(kind==='moderation')state.pass=false;await assert.rejects(api.checkCloudImage('cloud://env.bucket/private/owner/p.png'));assert.equal(state.saved.length,0);}});
test('development moderation switch does not bypass file validation or evidence archiving',async()=>{const {api,state}=auditFixture();state.enabled=false;await api.checkCloudImage('cloud://env.bucket/private/owner/p.png');assert.equal(state.saved.length,1);state.buffer=Buffer.from('not an image');await assert.rejects(api.checkCloudImage('cloud://env.bucket/private/owner/p.png'));});
test('text review uses trusted identity, segments long inputs and fails closed',async()=>{const {api,state}=auditFixture();await api.checkTextMulti({text:'x'.repeat(3601)});assert.equal(state.text.length,3);assert.ok(state.text.every(p=>p.openid==='owner'&&p.version===2&&p.content.length<=1800));state.pass=false;await assert.rejects(api.checkText('review me'));await assert.rejects(api.checkTextMulti({text:'x'.repeat(24001)}));});
function clientFixture(){const storage=new Map(),calls=[];let identity='user-a',admin=null,fail=true;const wx={getStorageSync:k=>storage.get(k),setStorageSync:(k,v)=>storage.set(k,v),removeStorageSync:k=>storage.delete(k)};const api=load('miniprogram/projects/crun/biz/operations_biz.js',{'../../../helper/cloud_helper.js':{async callCloudSumbit(route,params){calls.push({route,params});if(fail)throw new Error('offline');return {data:{ok:true}};}},'../../../comm/biz/passport_biz.js':{getUserId:()=>identity},'../../../comm/biz/admin_biz.js':{getAdminToken:()=>admin},'../../../lib/tools/md5_lib.js':{md5:s=>require('node:crypto').createHash('md5').update(s).digest('hex')}},{wx});return {api,storage,calls,setFail:v=>fail=v,setIdentity:v=>identity=v,setAdmin:v=>admin=v};}
test('weak network retries reuse command id without persisting personal payload',async()=>{const f=clientFixture(),p={id:'order',note:'secret-phone-13800138000'};await assert.rejects(f.api.command('mail/exception',p));await assert.rejects(f.api.command('mail/exception',p));assert.equal(f.calls[0].params.requestId,f.calls[1].params.requestId);assert.ok(!JSON.stringify([...f.storage]).includes(p.note));f.setFail(false);await f.api.command('mail/exception',p);assert.equal(f.storage.size,0);});
test('command cache isolates users, administrator sessions and changed payloads',async()=>{const f=clientFixture();const run=()=>assert.rejects(f.api.command('mail/accept',{id:'order'}));await run();f.setIdentity('user-b');await run();assert.notEqual(f.calls[0].params.requestId,f.calls[1].params.requestId);f.setAdmin({name:'a',token:'token1'});await assert.rejects(f.api.command('admin/operations_hold',{id:'order',note:'one'}));f.setAdmin({name:'a',token:'token2'});await assert.rejects(f.api.command('admin/operations_hold',{id:'order',note:'one'}));assert.equal(f.storage.size,4);await assert.rejects(f.api.command('mail/accept',{id:'order',note:'changed'}));assert.notEqual(f.calls[1].params.requestId,f.calls.at(-1).params.requestId);});
test('operation controller authenticates first, accepts absent status and requires mutation ids',async()=>{const dataCheck=require('../../cloudfunctions/mcloud/framework/validate/data_check.js');let params={},allowed=true,calls=0;class Base{async isAdmin(){if(!allowed)throw new Error('denied');}validateData(r){return dataCheck.check(params,r);}}class Service{async orders(page,status){calls++;return {page,status};}async holdMail(){calls++;}}const Controller=load('cloudfunctions/mcloud/project/crun/controller/admin/admin_operations_controller.js',{'./base_project_admin_controller.js':Base,'../../service/operations_service.js':Service,'../../service/operation_config_service.js':Service,'../../service/mail_service.js':Service,'../../../../framework/validate/content_check.js':{checkTextMultiAdmin:async()=>{}}});const c=new Controller();const result=await c.orders();assert.equal(result.page,1);assert.equal(result.status,undefined);allowed=false;await assert.rejects(c.orders(),/denied/);assert.equal(calls,1);allowed=true;params={id:'order',note:'reason'};await assert.rejects(c.hold());assert.equal(calls,1);});
test('database wrapper treats only missing documents as absent, never network errors',async()=>{const api=load('cloudfunctions/mcloud/project/crun/service/operation_store.js',{'../../../framework/cloud/cloud_base.js':{},'../../../config/config.js':{COLLECTION_PRFIX:'bx_'},'../../../framework/core/app_error.js':Error});let response={data:[]},error;const tx={collection:()=>({doc:()=>({get:async()=>{if(error)throw error;return response;}})})};assert.equal(await api.get(tx,'mail','id'),null);error=Object.assign(new Error('timeout'),{code:'NETWORK_ERROR'});await assert.rejects(api.get(tx,'mail','id'),/timeout/);error=Object.assign(new Error('document does not exist'),{code:'DOCUMENT_NOT_FOUND'});assert.equal(await api.get(tx,'mail','id'),null);});


test('publish page sends selected deadline after successful upload and guards repeated taps',async()=>{
 let page,release,fail=false;const calls=[],errors=[];const Ops={upload:async()=>{calls.push('upload');await new Promise(r=>release=r);if(fail)throw new Error('upload failed');return ['cloud://archived'];},command:async(route,p)=>{calls.push({route,p});return {_id:'order'};},error:e=>errors.push(e.message)};
 const mocks={'../../../biz/mail_ui_biz.js':require('../../miniprogram/projects/crun/biz/mail_ui_biz.js'),'../../../biz/operations_biz.js':Ops,'../../../../../helper/page_helper.js':{},'../../../../../helper/cloud_helper.js':{},'../../../../../helper/content_check_helper.js':{},'../../../biz/mail_biz.js':{CHECK_FORM:{}},'../../../../../helper/validate.js':{check:()=>({end:'2026-09-08 12:00',cateId:'1'})},'../../../../../comm/biz/public_biz.js':{removeCacheList(){}},'../../../biz/project_biz.js':{},'../../../../../comm/biz/passport_biz.js':{loginMustCancelWin:async()=>true}};
 load('miniprogram/projects/crun/pages/mail/add/mail_add.js',mocks,{Page:p=>page=p,wx:{showLoading(){},hideLoading(){},showModal(){}}});page.data={config:{enabled:true,offlineNotice:'线下结算'},campus:'育才校区'};page.setData=p=>Object.assign(page.data,p);page.selectComponent=()=>({getForms:()=>[{mark:'img',type:'image',val:['local']} ]});
 const first=page.bindFormSubmit();await new Promise(r=>setImmediate(r));await page.bindFormSubmit();assert.equal(calls.length,1);release();await first;assert.equal(calls[1].route,'mail/insert');assert.equal(calls[1].p.forms.find(f=>f.mark==='formEnd').val,'2026-09-08 12:00');assert.equal(calls[1].p.forms.find(f=>f.mark==='img').val[0],'cloud://archived');
 fail=true;const failed=page.bindFormSubmit();await new Promise(r=>setImmediate(r));release();await failed;assert.equal(calls.filter(x=>x.route).length,1);assert.equal(errors[0],'upload failed');assert.equal(page.data.submitting,false);
});


test('disabled payment methods return explicit business errors without touching cloud payment',async()=>{
 const AppError=require('../../cloudfunctions/mcloud/framework/core/app_error.js');
 const Base=load('cloudfunctions/mcloud/framework/platform/controller/base_controller.js',{'../../../config/config.js':{},'../../utils/time_util.js':{},'../../utils/util.js':{},'../../validate/data_check.js':{},'../../core/app_error.js':AppError,'../../core/app_code.js':{LOGIC:1600}});
 const Pay=load('cloudfunctions/mcloud/project/crun/controller/pay_controller.js',{'./base_project_controller.js':Base,'../../../framework/cloud/cloud_base.js':{getCloud(){throw new Error('unexpected payment call');}}});
 const controller=Object.create(Pay.prototype);await assert.rejects(controller.createPay(),e=>e.name==='AppError'&&/线下结算/.test(e.message));await assert.rejects(controller.refund(),e=>e.name==='AppError'&&/不执行退款/.test(e.message));
});
test('administrator sessions require matching identity, active account, unexpired token and correct role',async()=>{
 const row={ADMIN_TOKEN:'token',ADMIN_TOKEN_USER:'owner',ADMIN_TOKEN_TIME:Date.now(),ADMIN_STATUS:1,ADMIN_TYPE:1};
 class Base{AppError(message){throw new Error(message);}}
 const Model={async getOne(where){return Object.entries(where).every(([k,v])=>Array.isArray(v)?row[k]>v[1]:row[k]===v)?row:null;}};
 const Service=load('cloudfunctions/mcloud/framework/platform/service/base_admin_service.js',{'./base_service.js':Base,'../../../framework/utils/time_util.js':{time:Date.now},'../../../framework/core/app_code.js':{ADMIN_ERROR:2401},'../../../config/config.js':{ADMIN_LOGIN_EXPIRE:86400},'../model/admin_model.js':Model,'../model/log_model.js':{}});
 const svc=new Service();assert.equal(await svc.isAdmin('token','owner'),row);await assert.rejects(svc.isAdmin('token','other'));row.ADMIN_STATUS=0;await assert.rejects(svc.isAdmin('token','owner'));row.ADMIN_STATUS=1;row.ADMIN_TOKEN_TIME=0;await assert.rejects(svc.isAdmin('token','owner'));row.ADMIN_TOKEN_TIME=Date.now();row.ADMIN_TYPE=2;await assert.rejects(svc.isSuperAdmin('token','owner'));assert.equal(await svc.isAdmin('token','owner'),row);
});
