const Ops = require('../../biz/operations_biz.js');
const cloudHelper = require('../../../../helper/cloud_helper.js');
const validate = require('../../../../helper/validate.js');
const pageHelper = require('../../../../helper/page_helper.js');
const projectSetting = require('../../public/project_setting.js');
const ProfileBiz = require('../../biz/profile_biz.js');
const DEFAULT_CAMPUSES = ['育才校区', '王城校区', '雁山校区'];
const PERSONAL_MARKS = new Set(['sex', 'college', 'sub', 'payPic']);
async function loadCampuses(page) { try { const c = await Ops.get('operations/config'); const campuses = c && Array.isArray(c.campuses) ? c.campuses.filter(Boolean) : []; page.setData({ campuses: campuses.length ? campuses : DEFAULT_CAMPUSES }); } catch (_) { page.setData({ campuses: DEFAULT_CAMPUSES }); } }
function applyUser(page, user) { const p = ProfileBiz.readProfile(user); const campuses = page.data.campuses && page.data.campuses.length ? page.data.campuses : DEFAULT_CAMPUSES; page.setData(Object.assign({ formName: user.USER_NAME || '', formMobile: user.USER_MOBILE || '', formPic: user.USER_PIC || '', formForms: user.USER_FORMS || [], fields: projectSetting.USER_FIELDS }, p, { campuses, campusIndex: Math.max(0, campuses.indexOf(p.campus)), contactEditorVisible: false, addressEditorVisible: false, editingContactIndex: -1, editingAddressIndex: -1, contactDraft: { name: '', phone: '' }, addressDraft: { label: '', detail: '' } })); }
function bindProfileNameInput(e) { this.setData({ formName: e.detail.value }); }
function bindProfileMobileInput(e) { this.setData({ formMobile: e.detail.value }); }
function bindCampusChange(e) { const i = Number(e.detail.value); this.setData({ campusIndex: i, campus: this.data.campuses[i] || '' }); }
function bindContactInput(e) { this.setData({ ['contactDraft.' + e.currentTarget.dataset.field]: e.detail.value }); }
function bindAddressInput(e) { this.setData({ ['addressDraft.' + e.currentTarget.dataset.field]: e.detail.value }); }
function bindAddContact() { this.setData({ contactEditorVisible: true, editingContactIndex: -1, contactDraft: { name: '', phone: '' } }); }
function bindEditContact(e) { const i = Number(e.currentTarget.dataset.index); this.setData({ contactEditorVisible: true, editingContactIndex: i, contactDraft: Object.assign({}, this.data.contacts[i]) }); }
function bindSetDefaultContact(e) { const i = Number(e.currentTarget.dataset.index); this.setData({ contacts: ProfileBiz.normalizeContacts(this.data.contacts.map((x, n) => Object.assign({}, x, { isDefault: n === i }))) }); }
function bindDeleteContact(e) { const a = this.data.contacts.slice(); a.splice(Number(e.currentTarget.dataset.index), 1); this.setData({ contacts: ProfileBiz.normalizeContacts(a) }); }
function bindCancelContact() { this.setData({ contactEditorVisible: false, editingContactIndex: -1 }); }
function bindSaveContact() { const d = { name: String(this.data.contactDraft.name || '').trim(), phone: String(this.data.contactDraft.phone || '').trim() }; if (!d.name || !/^1[3-9]\d{9}$/.test(d.phone)) return pageHelper.showNoneToast('请填写正确的联系人和手机号'); const a = this.data.contacts.slice(); if (this.data.editingContactIndex >= 0) a[this.data.editingContactIndex] = d; else a.push(d); this.setData({ contacts: ProfileBiz.normalizeContacts(a), contactEditorVisible: false, editingContactIndex: -1 }); }
function bindAddAddress() { this.setData({ addressEditorVisible: true, editingAddressIndex: -1, addressDraft: { label: '', detail: '' } }); }
function bindEditAddress(e) { const i = Number(e.currentTarget.dataset.index); this.setData({ addressEditorVisible: true, editingAddressIndex: i, addressDraft: Object.assign({}, this.data.addresses[i]) }); }
function bindSetDefaultAddress(e) { const i = Number(e.currentTarget.dataset.index); this.setData({ addresses: ProfileBiz.normalizeAddresses(this.data.addresses.map((x, n) => Object.assign({}, x, { isDefault: n === i }))) }); }
function bindDeleteAddress(e) { const a = this.data.addresses.slice(); a.splice(Number(e.currentTarget.dataset.index), 1); this.setData({ addresses: ProfileBiz.normalizeAddresses(a) }); }
function bindCancelAddress() { this.setData({ addressEditorVisible: false, editingAddressIndex: -1 }); }
function bindSaveAddress() { const d = { label: String(this.data.addressDraft.label || '').trim() || '常用地址', detail: String(this.data.addressDraft.detail || '').trim() }; if (!d.detail) return pageHelper.showNoneToast('请填写详细地址'); const a = this.data.addresses.slice(); if (this.data.editingAddressIndex >= 0) a[this.data.editingAddressIndex] = d; else a.push(d); this.setData({ addresses: ProfileBiz.normalizeAddresses(a), addressEditorVisible: false, editingAddressIndex: -1 }); }
function markForms(personal, mark) { const i = personal.findIndex(x => x && x.mark === mark); return i; }
async function bindSubmitTap() { if (this.data.saving) return; this.setData({ saving: true, saveError: '' }); try { if (!String(this.data.campus || '').trim()) throw new Error('请选择所在校区'); const component = this.selectComponent('#cmpt-form'); if (!component || typeof component.getForms !== 'function') throw new Error('表单加载失败，请重试'); const got = component.getForms(true); if (!Array.isArray(got)) throw new Error('表单加载失败，请重试'); const personal = got.filter(x => x && PERSONAL_MARKS.has(x.mark)); const forms = (this.data.formForms || []).filter(x => x && !PERSONAL_MARKS.has(x.mark) && !['campus','contacts','addresses','address','commonContact','commonContactMobile'].includes(x.mark)).concat(personal); const contacts = ProfileBiz.normalizeContacts(this.data.contacts), addresses = ProfileBiz.normalizeAddresses(this.data.addresses); forms.push({ mark: 'campus', title: '所在校区', type: 'select', val: this.data.campus }, { mark: 'contacts', title: '常用联系人', type: 'json', val: contacts }, { mark: 'addresses', title: '常用地址', type: 'json', val: addresses }, { mark: 'address', title: '常用地址', type: 'text', val: (ProfileBiz.getDefaultItem(addresses) || {}).detail || '' }, { mark: 'commonContact', title: '常用联系人', type: 'text', val: (ProfileBiz.getDefaultItem(contacts) || {}).name || '' }, { mark: 'commonContactMobile', title: '联系人手机', type: 'text', val: (ProfileBiz.getDefaultItem(contacts) || {}).phone || '' }); const data = validate.check(Object.assign({}, this.data, { formForms: forms }), projectSetting.USER_CHECK_FORM, this); if (!data) return; wx.showLoading({ title: '保存中' }); const pic = await cloudHelper.transTempPicOne(this.data.formPic, 'user/', '', false); for (const item of forms) if (item.type === 'image' && Array.isArray(item.val)) item.val = await cloudHelper.transTempPics(item.val, 'user/'); await cloudHelper.callCloudSumbit(this.data.isEdit ? 'passport/edit_base' : 'passport/register', { name: this.data.formName, mobile: this.data.formMobile, pic, forms, status: projectSetting.USER_REG_CHECK ? 0 : 1 }, { title: '保存中' }); wx.hideLoading(); pageHelper.showSuccToast(this.data.isEdit ? '保存成功' : '注册成功', 1200, () => wx.reLaunch({ url: '../index/my_index' })); } catch (err) { wx.hideLoading(); const msg = err && err.message || '保存失败，请稍后重试'; this.setData({ saveError: msg }); pageHelper.showNoneToast(msg); } finally { this.setData({ saving: false }); } }
module.exports = { loadCampuses, applyUser, bindProfileNameInput, bindProfileMobileInput, bindCampusChange, bindContactInput, bindAddressInput, bindAddContact, bindEditContact, bindSetDefaultContact, bindDeleteContact, bindCancelContact, bindSaveContact, bindAddAddress, bindEditAddress, bindSetDefaultAddress, bindDeleteAddress, bindCancelAddress, bindSaveAddress, bindSubmitTap };
